### ISSUE TITLE
In progress

### ISSUE THREAD

**Issue by jesseleite** [statamic/migrator#4]
### Todo

- [x] Whole site migrator
- [x] Fieldset to blueprint migrator
    - [ ] Flesh out individual fieldtype migrations
        - [x] Assets fieldtype (relative paths, see #3)
        - [x] Partial fieldtype (now using `import`)
        - [x] Pages fieldtype (now using `entries`)
        - [x] Collection fieldtype (now using `entries`)
        - [ ] Suggest fieldtype (now using custom `relationship` fieldtype)
    - [x] Conditional fields syntax
- [x] Collection migrator
    - [ ] Changes to `mount` (see https://github.com/statamic/cms/issues/1352)
- [x] Pages migrator
- [x] Taxonomy migrator
- [x] Asset container migrator
- [x] Globals migrator
- [x] User migrator
- [x] Settings migrator
    - [ ] Flesh out settings migrator more
- [x] Theme migrator
    - [x] Copy active theme
    - [x] Migrate layouts and partials
    - [ ] Migrate tags and modifiers
- [x] User role migrator
- [x] User group migrator
- [x] Form migrator
- [ ] Localized content (right now only migrating sites config, not content)
- [ ] Site helpers

### Please Note

This package is still a work in progress.  If you run into any problems, or have any feature suggestions that are not listed above, feel free to [submit a new issue](https://github.com/statamic/migrator/issues/new) so that we can improve this migrator package for everyone ☺️

**Comment by axelferdinand** [comment]
I can see from the list above, that **Migrate layouts and partials** is checked. I've always had only one layout file (default.html) where head and body is placed, referring to {{ template_content }} for templates. From what I can see, the Migrator doesn't merge the default.html layout file with the templates, so when entering one of the new templates in the frontend, only the template content is printed - head, footer and the rest of the markup in layout.html is lacking. Does this merge need to be done manually?

**Comment by jesseleite** [comment]
@axelferdinand Will look into this again thanks!  Closing this issue though, but created another over at https://github.com/statamic/migrator/issues/43

**Comment by jesseleite** [comment]
Moved the remaining things to separate issues.
